#!/bin/bash
# sys_info_page: программа вывода страницы с информацией о системе
PROGNAME=$(basename $0)
TITLE="System Information Report For $HOSTNAME"
CURRENT_TIME=$(date +"%x %r %Z")
TIME_STAMP="Generated $CURRENT_TIME, by $USER"

report_uptime () {
	cat <<- _EOF_
	<H2>System Uptime</H2>
	<PRE>$(uptime)</PRE>
	_EOF_
return
}

report_disk_space () {
	cat <<- _EOF_
	<H2>Disk Space Utilization</H2>

	<PRE>$(df -h)</PRE>
	_EOF_
return
}

report_home_space () {
	local format="%8s%10s%10s\n"
	local i dir_list total_files total_dirs total_size user_name
	if [[ $(id -u) -eq 0 ]]; then
		dir_list=/home/*
		user_name="All Users"
	else
		dir_list=$HOME
		user_name=$USER
	fi
	echo "<H2>Home Space Utilization ($user_name)</H2>"
	for i in $dir_list; do
		total_files=$(find $i -type f | wc -l)
		total_dirs=$(find $i -type d | wc -l)
		total_size=$(du -sh $i | cut -f 1)
		echo "<H3>$i</H3>"
		echo "<PRE>"
		printf "$format" "Dirs" "Files" "Size"
		printf "$format" "----" "-----" "----"

		printf "$format" $total_dirs $total_files $total_size
		echo "</PRE>"
	done
return
}

usage () {
	echo "$PROGNAME: usage: $PROGNAME [-f file | -i]"
	return
}

write_html_page () {
	cat <<- _EOF_
	<HTML>
		<HEAD>
			<TITLE>$TITLE</TITLE>
		</HEAD>
		<BODY>
			<H1>$TITLE</H1>
			<P>$TIME_STAMP</P>
	_EOF_

	if [ "$1" == "1" ]; then
		cat <<- _EOF_
		$(report_uptime)
		_EOF_
	fi
	if [ "$2" == "1" ]; then
		cat <<- _EOF_
		$(report_disk_space)
		_EOF_
	fi
	if [ "$3" == "1" ]; then
		cat <<- _EOF_
		$(report_home_space)
		_EOF_
	fi
	cat <<- _EOF_
		</BODY>
	</HTML>
	_EOF_
return
}

# обработка параметров командной строки

filename="taks.html"

# вывод страницы html
if [[ -n $filename ]]; then
	if touch $filename && [[ -f $filename ]]; then
		choice=$(dialog --menu "Выберите элементы из списка" 15 50 6 \
			1 "report uptime" \
			2 "report disk space" \
			3 "report home space" \
			4 "usage" \
			5 "View all the information" \
			6 "Выход" 3>&1 1>&2 2>&3)

		case $choice in
			1)
				write_html_page "1" "0" "0" > $filename
				;;
			2)
				write_html_page "0" "1" "0" > $filename
				;;
			3)
				write_html_page "0" "0" "1" > $filename
				;;
			4)
				usage
				exit 1
				;;
			5)
				write_html_page "1" "1" "1" > $filename
				;;
			6)
				exit 1
				;;
		esac
		xdg-open "$filename"
	else
		echo "$PROGNAME: Cannot write file '$filename'" >&2
		exit 1
	fi
else
	write_html_page
fi

