#!/bin/bash
SRC="/home/user/school/Linux/Lab1_4/source"
DEST="/home/user/school/Linux/Lab1_4/destination"
inotifywait -m -r -e modify,create,delete,move "$SRC" --format '%w%f' | while read FILE
do
    rsync -avz "$SRC" "$DEST"
done

